package se.deluxerpanda.short_message_service.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF004F6B)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF2E7494)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4A616F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD1EAFA)
val onSecondaryContainerLight = Color(0xFF364D5A)
val tertiaryLight = Color(0xFF5E3A6E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF845E94)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F9FC)
val onBackgroundLight = Color(0xFF191C1E)
val surfaceLight = Color(0xFFF8F9FC)
val onSurfaceLight = Color(0xFF191C1E)
val surfaceVariantLight = Color(0xFFDCE4EA)
val onSurfaceVariantLight = Color(0xFF40484D)
val outlineLight = Color(0xFF70787E)
val outlineVariantLight = Color(0xFFC0C8CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3133)
val inverseOnSurfaceLight = Color(0xFFEFF1F3)
val inversePrimaryLight = Color(0xFF8ECFF2)
val surfaceDimLight = Color(0xFFD8DADD)
val surfaceBrightLight = Color(0xFFF8F9FC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F6)
val surfaceContainerLight = Color(0xFFECEEF1)
val surfaceContainerHighLight = Color(0xFFE6E8EB)
val surfaceContainerHighestLight = Color(0xFFE1E3E5)


val primaryDark = Color(0xFF8ECFF2)
val onPrimaryDark = Color(0xFF003548)
val primaryContainerDark = Color(0xFF015B7A)
val onPrimaryContainerDark = Color(0xFFF0F8FF)
val secondaryDark = Color(0xFFB2CAD9)
val onSecondaryDark = Color(0xFF1C333F)
val secondaryContainerDark = Color(0xFF2B424F)
val onSecondaryContainerDark = Color(0xFFBFD8E7)
val tertiaryDark = Color(0xFFE3B7F3)
val onTertiaryDark = Color(0xFF442254)
val tertiaryContainerDark = Color(0xFF6B477B)
val onTertiaryContainerDark = Color(0xFFFFF6FC)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111416)
val onBackgroundDark = Color(0xFFE1E3E5)
val surfaceDark = Color(0xFF111416)
val onSurfaceDark = Color(0xFFE1E3E5)
val surfaceVariantDark = Color(0xFF40484D)
val onSurfaceVariantDark = Color(0xFFC0C8CE)
val outlineDark = Color(0xFF8A9298)
val outlineVariantDark = Color(0xFF40484D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E3E5)
val inverseOnSurfaceDark = Color(0xFF2E3133)
val inversePrimaryDark = Color(0xFF196584)
val surfaceDimDark = Color(0xFF111416)
val surfaceBrightDark = Color(0xFF363A3C)
val surfaceContainerLowestDark = Color(0xFF0B0F11)
val surfaceContainerLowDark = Color(0xFF191C1E)
val surfaceContainerDark = Color(0xFF1D2022)
val surfaceContainerHighDark = Color(0xFF272A2D)
val surfaceContainerHighestDark = Color(0xFF323537)









