package se.deluxerpanda.short_message_service.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5E81AC)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E4F2)
val onPrimaryContainerLight = Color(0xFF002244)
val secondaryLight = Color(0xFF81A1C1)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE0F5)
val onSecondaryContainerLight = Color(0xFF1B2A40)
val tertiaryLight = Color(0xFFA3BE8C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFDDEEDD)
val onTertiaryContainerLight = Color(0xFF1E3921)
val errorLight = Color(0xFFBF616A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF2C9CC)
val onErrorContainerLight = Color(0xFF3B2022)
val backgroundLight = Color(0xFFF1F5F9)
val onBackgroundLight = Color(0xFF2E3440)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF2E3440)
val surfaceVariantLight = Color(0xFFE5E9F0)
val onSurfaceVariantLight = Color(0xFF434C5E)
val outlineLight = Color(0xFFB0BEC5)
val outlineVariantLight = Color(0xFFB0BEC5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3440)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFF88C0D0)
val surfaceDimLight = Color(0xFFF1F5F9)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F5F9)
val surfaceContainerLight = Color(0xFFE5E9F0)
val surfaceContainerHighLight = Color(0xFFD8DEE9)
val surfaceContainerHighestLight = Color(0xFFB0BEC5)




val primaryDark = Color(0xFF88C0D0)
val onPrimaryDark = Color(0xFF2E3440)
val primaryContainerDark = Color(0xFF4C566A)
val onPrimaryContainerDark = Color(0xFFD8DEE9)
val secondaryDark = Color(0xFF81A1C1)
val onSecondaryDark = Color(0xFF2E3440)
val secondaryContainerDark = Color(0xFF88C0D0)
val onSecondaryContainerDark = Color(0xFF2E3440)
val tertiaryDark = Color(0xFFA3BE8C)
val onTertiaryDark = Color(0xFF2E3440)
val tertiaryContainerDark = Color(0xFF4C566A)
val onTertiaryContainerDark = Color(0xFFE5E9F0)
val errorDark = Color(0xFFBF616A)
val onErrorDark = Color(0xFF2E3440)
val errorContainerDark = Color(0xFF4C566A)
val onErrorContainerDark = Color(0xFFECEFF4)
val backgroundDark = Color(0xFF2E3440)
val onBackgroundDark = Color(0xFFD8DEE9)
val surfaceDark = Color(0xFF3B4252)
val onSurfaceDark = Color(0xFFE5E9F0)
val surfaceVariantDark = Color(0xFF4C566A)
val onSurfaceVariantDark = Color(0xFFD8DEE9)
val outlineDark = Color(0xFF4C566A)
val outlineVariantDark = Color(0xFF4C566A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFD8DEE9)
val inverseOnSurfaceDark = Color(0xFF2E3440)
val inversePrimaryDark = Color(0xFF5E81AC)
val surfaceDimDark = Color(0xFF3B4252)
val surfaceBrightDark = Color(0xFF4C566A)
val surfaceContainerLowestDark = Color(0xFF2E3440)
val surfaceContainerLowDark = Color(0xFF3B4252)
val surfaceContainerDark = Color(0xFF434C5E)
val surfaceContainerHighDark = Color(0xFF4C566A)
val surfaceContainerHighestDark = Color(0xFF5E81AC)








