
on:

  workflow_dispatch:

name: Extract Android Info

jobs:
  extract-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from build.gradle
        id: extract_version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle.kts | sed 's/versionName = //;s/"//g' | xargs)
          
          echo "VERSION_NAME=$VERSION_NAME"

          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Use extracted information
        run: |
          echo "Version: ${{ steps.extract_version.outputs.version_name }}"
